### ISSUE TITLE
Klaida generuojant lipduką - field":"receiver#terminalId","message":"Unsupported value

### ISSUE THREAD

**Issue by darka84** [eshoper/woo-lithuaniapost#13]
Generuojant lipduką grąžina klaidą:

{"fieldValidationErrors":[],"valueValidationErrors":[{"field":"receiver#terminalId","message":"Unsupported value. Unique error identifier: XZ-0815","code":"UNSUPPORTED"}]}

Terminalas pasirinktas iš sąrašo.

**Comment by eshoper** [comment]
Dėl šių techninių kliučių prašome kreiptis tiesiogiai pagalba@eshoper.lt.
