### ISSUE TITLE
Generuojant lipduką grąžina klaidą - field":"extension#2","message":"Unsupported value

### ISSUE THREAD

**Issue by darka84** [eshoper/woo-lithuaniapost#14]
Užsakyme rankiniu būdu pakeitus siuntos dydi nebegeneruoja lipduko.

{"fieldValidationErrors":[],"valueValidationErrors":[{"field":"extension#2","message":"Unsupported value. Unique error identifier: XR-3149","code":"UNSUPPORTED"}]}

**Comment by eshoper** [comment]
Dėl šių techninių kliučių prašome kreiptis tiesiogiai pagalba@eshoper.lt.
